from typing import Dict, Literal

type LanguageID = Literal["zh_cn", "en_us"]
type LANGType = Dict[LanguageID, Dict[str, str]]


Lang: LANGType = {
	"zh_cn": {
        "ui.text.tip": "提示：%s",
        "ui.text.tip.exit": "按下Ctrl+C退出此页面。",
        "ui.text.tip.exit.undo": "按下Ctrl+C以退出，将不会进行操作。",
        "ui.text.tip.bool": "输入y/n来指定布尔值。",
        "ui.text.tip.list": "输入列表字面量以解析。示例：['hello', 123, True]",
        "ui.text.tip.default": "输入为空时使用默认值：%s。",
        "ui.text.tip.current": "当前值：%s",
        "ui.text.input": "输入：",
        "ui.text.exit": "已退出此页面。",
        "ui.text.error": "异常：%s",
        "ui.text.error.empty": "异常：输入为空。",
        "ui.text.error.type": "异常：数据类型错误，应为%s类型。",
        "ui.text.error.type.value": "异常：数据类型错误，应为%s类型，取值范围：0 - %d。",
        "ui.text.error.value.bool": "异常：数据内容错误，应为y/n。",
        "ui.text.error.value.list": "异常：数据内容错误，应为%s字面量。",
        "ui.text.error.index": "异常：索引溢出，取值范围：0 - %d。",
        "ui.text.edit": "修改成功，已退出此页面。",
        "ui.text.enter": "按下回车键以继续。",

        "core.jvm.args.info.Xmn": "新生代内存大小（GB）",
        "core.jvm.args.info.server": "服务器模式JIT",
        "core.jvm.args.info.XX_UseG1GC": "G1垃圾回收器",
        "core.jvm.args.info.XX_MaxGCPauseMillis": "最大GC暂停时间（MS）",
        "core.jvm.args.info.XX_MaxGCPauseMillis.range": "取值范围：50~1000",
        "core.jvm.args.info.XX_G1HeapRegionSize": "G1堆区域大小（MB）",
        "core.jvm.args.info.XX_MetaspaceSize": "元空间初始大小（MB）",
        "core.jvm.args.info.XX_MaxMetaspaceSize": "元空间最大大小（MB）",
        "core.jvm.args.info.XX_UseZGC": "ZGC垃圾回收器",
        "core.jvm.args.info.XX_UseShenandoahGC": "Shenandoah垃圾回收器",
        "core.jvm.args.info.XX_DisableExplicitGC": "禁用System.gc()调用",
        "core.jvm.args.info.XX_UseStringDeduplication": "开启字符串去重",
        "core.jvm.args.info.XX_AlwaysPreTouch": "启动时预分配内存",
        "core.jvm.args.info.XX_ParallelRefProcEnabled": "启用并行引用处理",
        "core.jvm.args.info.XX_UnlockExperimentalVMOptions": "解锁实验性VM选项",
        "core.jvm.args.info.XX_UseLargePages": "使用大内存页",
        "core.jvm.args.info.XX_UseTransparentHugePages": "使用透明大页",
        "core.jvm.args.info.XX_TieredCompilation": "启用分层编译",
        "core.jvm.args.info.XX_OptimizeStringConcat": "优化字符串连接操作",
        "core.jvm.args.info.XX_UseCodeCacheFlushing": "启用代码缓存清理",
        "core.jvm.args.info.XX_PerfDisableSharedMem": "禁用性能数据共享内存",
        "core.jvm.args.info.XX_UseBiasedLocking": "启用偏向锁",
        "core.jvm.args.info.XX_UseCompressedOops": "启用压缩对象指针",
        "core.jvm.args.info.XX_UseCompressedClassPointers": "启用压缩类指针",

        "core.text.error.jdk.version": "⚠JDK版本异常警告",
        "core.text.error.jdk.version.tip": "JDK应为%s版本。",
        "core.text.tip.module.schedule.missing": "'schedule'模块未安装，建议运行 'pip install schedule' 命令以使用备份功能。",

        "core.text.reboot.time": "重启次数：%d",
        "core.text.run.command": "启动命令：%s",
        "core.text.start.pid": "服务器已启动，进程PID：%d",
        "core.text.stop.code": "服务器已关闭，返回代码：%d",
        "core.text.reboot.ticks": "重启倒计时：%ds",
        "core.text.backup.complete": "备份已完成。",
        "core.text.error.backup.format": "⚠ 备份时间格式错误：%s，应为 HH:MM 或 HH:MM:SS",
        "core.text.delete.file": "已删除文件：%s",

        "tool.text.delete": "删除：%s",
        "tool.text.error.run": "执行命令失败: %s",
        "tool.text.error.info": "获取网络信息出错: %s",

        "main.text.run.server.desc": "再次按下任意键，以启动服务器。",
        "main.text.multi.run.server.desc": "请输入重启次数。",
        "main.text.multi.run.server.prompt": "输入负值可无限循环。",
        "main.text.jvm.args.config.list.desc": "确定生成JVM参数吗？",
        "main.text.jvm.args.config.list.prompt": "建议值：%s",
        "main.text.jvm.args.config.text.list.desc": "自动生成适宜的JVM参数",
        "main.text.jvm.args.config.desc": "请选择将要修改的参数。",

        "main.text.backup.config.desc": "请选择将要修改的配置。",
        "main.text.backup.config.text1": "配置启用备份功能",
        "main.text.backup.config.text2": "配置备份时间列表",
        "main.text.backup.config.text3": "配置最大备份数量",
        "main.text.backup.config.text4": "配置备份文件目录",
        "main.text.backup.config.text4.prompt": "示例：backup/",

        "main.text.config.desc": "请选择将要修改的配置。",
        "main.text.config.text1": "配置初始堆内存大小（GB）",
        "main.text.config.text2": "配置最大堆内存大小（GB）",
        "main.text.config.text3": "配置核心文件名称",
        "main.text.config.text3.prompt": "请注意输入文件拓展名：.jar",
        "main.text.config.text4": "配置模组加载器",
        "main.text.config.text5": "配置游戏版本",
        "main.text.config.text6": "配置JDK绝对路径",
        "main.text.config.text6.prompt": "请注意输入完整的绝对路径。\n示例：C:/Program Files/Zulu/zulu-17",
        "main.text.config.text7": "配置重启等待时间（秒）",
        "main.text.config.text8": "配置高级JVM参数",
        "main.text.config.text9": "配置备份计划任务",

        "main.text.env.desc": "运行环境信息。",
        "main.text.clean.desc": "选择清理等级",
        "main.text.clean.prompt": "[0] 日志+缓存 [1] 日志+临时数据 [2] 重置",
        "main.text.net.desc": "网络信息",
        "main.text.eula.desc": "再次按下任意键，以修改eula.txt。",
        "main.text.eula.text": "继续前，请先阅读并同意此协议：%s",
        "main.text.tool.desc": "选择要执行的功能",
        "main.text.tool.text1": "检测运行环境",
        "main.text.tool.text2": "清理文件数据",
        "main.text.tool.text3": "查看网络信息",
        "main.text.tool.text4": "修改EULA协议",

        "main.text.ui.desc": "请选择将要使用的功能。",
        "main.text.ui.text1": "启动服务器",
        "main.text.ui.text2": "启动服务器（自动重启）",
        "main.text.ui.text3": "修改配置",
        "main.text.ui.text4": "其他工具",
	},
    "en_us": {
        "ui.text.tip": "Tip: %s",
        "ui.text.tip.exit": "Press Ctrl+C to exit this page.",
        "ui.text.tip.exit.undo": "Press Ctrl+C to exit, no operation will be performed.",
        "ui.text.tip.bool": "Enter y/n to specify a boolean value.",
        "ui.text.tip.list": "Enter a list literal to parse. Example: ['hello', 123, True]",
        "ui.text.tip.default": "Use default value when input is empty: %s.",
        "ui.text.tip.current": "Current value: %s",
        "ui.text.input": "Input: ",
        "ui.text.exit": "Exited this page.",
        "ui.text.error": "Error: %s",
        "ui.text.error.empty": "Error: Empty input.",
        "ui.text.error.type": "Error: Data type error, expected %s type.",
        "ui.text.error.type.value": "Error: Data type error, expected %s type, value range: 0 - %d.",
        "ui.text.error.value.bool": "Error: Data content error, expected y/n.",
        "ui.text.error.value.list": "Error: Data content error, expected %s literal.",
        "ui.text.error.index": "Error: Index out of range, valid range: 0 - %d.",
        "ui.text.edit": "Modification successful, exited this page.",
        "ui.text.enter": "Press Enter to continue.",

        "core.jvm.args.info.Xmn": "Young generation memory size (GB)",
        "core.jvm.args.info.server": "Server mode JIT",
        "core.jvm.args.info.XX_UseG1GC": "G1 garbage collector",
        "core.jvm.args.info.XX_MaxGCPauseMillis": "Maximum GC pause time (MS)",
        "core.jvm.args.info.XX_MaxGCPauseMillis.range": "Range: 50~1000",
        "core.jvm.args.info.XX_G1HeapRegionSize": "G1 heap region size (MB)",
        "core.jvm.args.info.XX_MetaspaceSize": "Initial metaspace size (MB)",
        "core.jvm.args.info.XX_MaxMetaspaceSize": "Maximum metaspace size (MB)",
        "core.jvm.args.info.XX_UseZGC": "ZGC garbage collector",
        "core.jvm.args.info.XX_UseShenandoahGC": "Shenandoah garbage collector",
        "core.jvm.args.info.XX_DisableExplicitGC": "Disable System.gc() calls",
        "core.jvm.args.info.XX_UseStringDeduplication": "Enable string deduplication",
        "core.jvm.args.info.XX_AlwaysPreTouch": "Pre-allocate memory at startup",
        "core.jvm.args.info.XX_ParallelRefProcEnabled": "Enable parallel reference processing",
        "core.jvm.args.info.XX_UnlockExperimentalVMOptions": "Unlock experimental VM options",
        "core.jvm.args.info.XX_UseLargePages": "Use large memory pages",
        "core.jvm.args.info.XX_UseTransparentHugePages": "Use transparent huge pages",
        "core.jvm.args.info.XX_TieredCompilation": "Enable tiered compilation",
        "core.jvm.args.info.XX_OptimizeStringConcat": "Optimize string concatenation",
        "core.jvm.args.info.XX_UseCodeCacheFlushing": "Enable code cache flushing",
        "core.jvm.args.info.XX_PerfDisableSharedMem": "Disable performance data shared memory",
        "core.jvm.args.info.XX_UseBiasedLocking": "Enable biased locking",
        "core.jvm.args.info.XX_UseCompressedOops": "Enable compressed object pointers",
        "core.jvm.args.info.XX_UseCompressedClassPointers": "Enable compressed class pointers",

        "core.text.error.jdk.version": "⚠JDK Version Warning",
        "core.text.error.jdk.version.tip": "JDK should be version %s.",
        "core.text.tip.module.schedule.missing": "'schedule' module not installed, it's recommended to run 'pip install schedule' to use backup functionality.",

        "core.text.reboot.time": "Restart count: %d",
        "core.text.run.command": "Startup command: %s",
        "core.text.start.pid": "Server started, process PID: %d",
        "core.text.stop.code": "Server stopped, return code: %d",
        "core.text.reboot.ticks": "Restart countdown: %ds",
        "core.text.backup.complete": "Backup completed.",
        "core.text.error.backup.format": "⚠ Backup time format error: %s, expected HH:MM or HH:MM:SS",
        "core.text.delete.file": "File deleted: %s",

        "tool.text.delete": "Deleting: %s",
        "tool.text.error.run": "Failed to execute command: %s",
        "tool.text.error.info": "Error getting network information: %s",

        "main.text.run.server.desc": "Press any key again to start the server.",
        "main.text.multi.run.server.desc": "Please enter the number of restarts.",
        "main.text.multi.run.server.prompt": "Enter a negative value for infinite loop.",
        "main.text.jvm.args.config.list.desc": "Generate JVM parameters?",
        "main.text.jvm.args.config.list.prompt": "Suggested values: %s",
        "main.text.jvm.args.config.text.list.desc": "Automatically generate suitable JVM parameters",
        "main.text.jvm.args.config.desc": "Please select the parameters to modify.",

        "main.text.backup.config.desc": "Please select the configuration to modify.",
        "main.text.backup.config.text1": "Configure backup function enable",
        "main.text.backup.config.text2": "Configure backup time list",
        "main.text.backup.config.text3": "Configure maximum backup count",
        "main.text.backup.config.text4": "Configure backup file directory",
        "main.text.backup.config.text4.prompt": "Example: backup/",

        "main.text.config.desc": "Please select the configuration to modify.",
        "main.text.config.text1": "Configure initial heap memory size (GB)",
        "main.text.config.text2": "Configure maximum heap memory size (GB)",
        "main.text.config.text3": "Configure core file name",
        "main.text.config.text3.prompt": "Please note to include the file extension: .jar",
        "main.text.config.text4": "Configure mod loader",
        "main.text.config.text5": "Configure game version",
        "main.text.config.text6": "Configure JDK absolute path",
        "main.text.config.text6.prompt": "Please enter the complete absolute path.\nExample: C:/Program Files/Zulu/zulu-17",
        "main.text.config.text7": "Configure restart wait time (seconds)",
        "main.text.config.text8": "Configure advanced JVM parameters",
        "main.text.config.text9": "Configure backup schedule",

        "main.text.env.desc": "Runtime environment information.",
        "main.text.clean.desc": "Select cleanup level",
        "main.text.clean.prompt": "[0] Logs+Cache [1] Logs+Temp Data [2] Reset",
        "main.text.net.desc": "Network information",
        "main.text.eula.desc": "Press any key again to modify eula.txt.",
        "main.text.eula.text": "Before proceeding, please read and agree to this agreement: %s",
        "main.text.tool.desc": "Select function to execute",
        "main.text.tool.text1": "Check runtime environment",
        "main.text.tool.text2": "Clean file data",
        "main.text.tool.text3": "View network information",
        "main.text.tool.text4": "Modify EULA agreement",

        "main.text.ui.desc": "Please select the function to use.",
        "main.text.ui.text1": "Start server",
        "main.text.ui.text2": "Start server (auto-restart)",
        "main.text.ui.text3": "Modify configuration",
        "main.text.ui.text4": "Other tools",
    }
}